[package]
name = "kraster2d"
version = "0.1.0"
edition = "2024"

[dependencies]
kmath = { path = "../kmath" }
kpix = { path = "../kpix" }
kimgfmt = { path = "../kimgfmt" }

[dev-dependencies]
kdev = { path = "../kdev" }
